services:
  zookeeper:
    image: 'registry.biubiubiu.io/turbine/bitnami-zookeeper:3.7.0-debian-10-r215'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'registry.biubiubiu.io/turbine/bitnami-kafka:2.4.1-debian-10-r58'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=EXTERNAL_PLAINTEXT://:9092,INTERNAL_PLAINTEXT://:9093
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL_PLAINTEXT://localhost:9092,INTERNAL_PLAINTEXT://kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper