a2.sources = s1
a2.channels = c1 c2
a2.sinks = k1 k2

a2.sources.s1.type = avro
a2.sources.s1.bind = 0.0.0.0
a2.sources.s1.port = 41414
a2.sources.s1.batchSize = 200
a2.sources.s1.compression-type = deflate
a2.sources.s1.channels = c1 

#a2.sources.s1.interceptors = i1 i2
#a2.sources.s1.interceptors.i1.type = cn.doitedu.log_collect.flume.LogTimeExtract$ExtractorBuilder
#a2.sources.s1.interceptors.i1.keyname = timestamp
#a2.sources.s1.interceptors.i2.type = cn.doitedu.log_collect.flume.ChannelSelectorHeader$ChannelSelectorHeaderBuilder

#轮询选择器，channel 可以利用多磁盘存储
#a2.sources.s1.channels = c1 c2
#a2.sources.s1.selector.type = load_balancing
#a2.sources.s1.selector.policy = round_robin
#多路复用选择器，用于数据分发
#a2.sources.s1.selector.type = multiplexing
#a2.sources.s1.selector.header = state
#a2.sources.s1.selector.mapping.CZ = c1
#a2.sources.s1.selector.mapping.US = c2 c3
#a2.sources.s1.selector.default = c1

a2.channels.c1.type = file
a2.channels.c1.dataDirs = /var/lib/flume/l2/channel/data1
a2.channels.c1.useDualCheckpoints = false
a2.channels.c1.checkpointDir = /var/lib/flume/l2/channel/ck1
a2.channels.c1.capacity = 1000000
a2.channels.c1.transactionCapacity = 10000

a2.channels.c2.type = file
a2.channels.c2.dataDirs = /var/lib/flume/l2/channel/data2
a2.channels.c2.useDualCheckpoints = false
a2.channels.c2.checkpointDir = /var/lib/flume/l2/channel/ck2
a2.channels.c2.capacity = 1000000
a2.channels.c2.transactionCapacity = 10000

a2.sinks.k1.channel = c1
a2.sinks.k1.type = hdfs
a2.sinks.k1.hdfs.path = hdfs://mycluster/logdata/applog/%Y-%m-%d
#如果 false 默认从 header timestamp key 中读取
a2.sinks.k1.hdfs.useLocalTimeStamp = true
a2.sinks.k1.hdfs.fileType = CompressedStream
a2.sinks.k1.hdfs.codeC = gzip
a2.sinks.k1.hdfs.fileSuffix = .gz
#a2.sinks.k1.hdfs.filePrefix = app-log
a2.sinks.k1.batch-size = 200
a2.sinks.k1.hdfs.rollInterval = 60
a2.sinks.k1.hdfs.rollSize = 134217728
a2.sinks.k1.hdfs.rollCount = 0

a2.sinks.k2.channel = c2
a2.sinks.k2.type = hdfs
a2.sinks.k2.hdfs.path = hdfs://mycluster/logdata/applog/%Y-%m-%d
a2.sinks.k2.hdfs.useLocalTimeStamp = true
a2.sinks.k1.hdfs.fileType = CompressedStream
a2.sinks.k1.hdfs.codeC = gzip
a2.sinks.k1.hdfs.fileSuffix = .gz
#a2.sinks.k1.hdfs.filePrefix = app-log
a1.sinks.k2.batch-size = 200
a2.sinks.k2.hdfs.rollInterval = 60
a2.sinks.k2.hdfs.rollSize = 134217728
a2.sinks.k2.hdfs.rollCount = 0