server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: springboot-kafka
  kafka:
    template:
      observation-enabled: true
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer