a1.sources = s1
a1.channels = c1
a1.sinks = k1 k2

a1.sources.s1.channels = c1
a1.sources.s1.type = TAILDIR
a1.sources.s1.positionFile = /var/lib/flume/l1/taildir/position.json
a1.sources.s1.filegroups = g1
a1.sources.s1.filegroups.g1 = /datagen/data/log/app.access.log.*
a1.sources.s1.batchSize = 200
a1.sources.s1.writePosInterval = 5000
#a1.sources.s1.headers.g1.log_type = applog
#a1.sources.s1.byteOffsetHeader = true
#a1.sources.s1.byteOffsetHeaderKey = byteoffset
#a1.sources.s1.fileHeader = true
#a1.sources.s1.fileHeaderKey = file

a1.channels.c1.type = file
a1.channels.c1.dataDirs = /var/lib/flume/l1/channel/data
a1.channels.c1.useDualCheckpoints = false
a1.channels.c1.checkpointDir = /var/lib/flume/l1/channel/ck
#存放的 event 最大数量
a1.channels.c1.capacity = 1000000
#一个事务能控制的 event 数量 
a1.channels.c1.transactionCapacity = 10000

a1.sinks.k1.channel = c1
a1.sinks.k1.type = avro
a1.sinks.k1.hostname = flume-l2
a1.sinks.k1.port = 41414
a1.sinks.k1.batch-size = 200
a1.sinks.k1.compression-type = deflate
a1.sinks.k1.compression-level = 6

a1.sinks.k2.channel = c1
a1.sinks.k2.type = avro
a1.sinks.k2.hostname = flume-l2
a1.sinks.k2.port = 41414
a1.sinks.k2.batch-size = 200
a1.sinks.k2.compression-type = deflate
a1.sinks.k2.compression-level = 6

a1.sinkgroups = kg1
a1.sinkgroups.kg1.sinks = k1 k2
a1.sinkgroups.kg1.processor.type = failover
a1.sinkgroups.kg1.processor.priority.k1 = 5
a1.sinkgroups.kg1.processor.priority.k2 = 10
a1.sinkgroups.kg1.processor.maxpenalty = 10000



