services:
  redis:
    image: redis:6.2.7
    ports:
      - 6379:6379

  zookeeper:
    image: 'bitnami/zookeeper:3.8.0-debian-11-r21'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2.8.1-debian-11-r7'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
