version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: booster
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init-table.sh
  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"