services:
  zookeeper:
    image: 'registry.biubiubiu.io/turbine/bitnami-zookeeper:3.7.0-debian-10-r215'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'registry.biubiubiu.io/turbine/bitnami-kafka:2.4.1-debian-10-r58'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NUM_PARTITIONS=10
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=EXTERNAL_PLAINTEXT://:9092,INTERNAL_PLAINTEXT://:9093
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL_PLAINTEXT://127.0.0.1:9092,INTERNAL_PLAINTEXT://kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  server:
    image: registry.biubiubiu.io/turbine/vertx:1.0-SNAPSHOT
    ports:
      - '8080:8080'
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./demo/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - server

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./demo/provision-datasource-prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./demo/provision-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./demo/ingest-v3.json:/etc/dashboards/funnydb/ingest-v3.json