version: '3'

networks:
  cluster-network:
    name: cluster-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24

services:
  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    networks:
      cluster-network:
        ipv4_address: 172.18.0.3
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker:
    image: bitnami/kafka:2.8.1
    container_name: broker
    hostname: broker
    networks:
      cluster-network:
        ipv4_address: 172.18.0.4
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://broker:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  redis:
    image: redis
    container_name: redis
    hostname: redis
    networks:
      cluster-network:
        ipv4_address: 172.18.0.5
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  clickhouse1:
    image: clickhouse/clickhouse-server:22.7.2.15
    container_name: clickhouse1
    hostname: clickhouse1
    networks:
      cluster-network:
        ipv4_address: 172.18.0.6
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config1.xml:/etc/clickhouse-server/config.xml
    ports:
      - 8121:8123
      - 9001:9000
    depends_on:
      - zookeeper

  clickhouse2:
    image: clickhouse/clickhouse-server:22.7.2.15
    container_name: clickhouse2
    hostname: clickhouse2
    networks:
      cluster-network:
        ipv4_address: 172.18.0.7
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config2.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 8122:8123
      - 9002:9000
    depends_on:
      - zookeeper
      - clickhouse1

  master:
    image: bitnami/spark:3.2.2
    container_name: master
    networks:
      cluster-network:
        ipv4_address: 172.18.0.8
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HADOOP_USER_NAME=hdfsuser
    ports:
      - 4040:4040
      - 8080:8080
      - 7077:7077
    volumes:
      - ./../../target:/spark_src
      - ./commit.sh:/commit.sh
      - ./log4j.properties:/opt/bitnami/spark/conf/log4j.properties
      - ./core-site.xmlaaa:/opt/bitnami/spark/conf/core-site.xmlaaa
  worker1:
    image: bitnami/spark:3.2.2
    container_name: worker1
    networks:
      cluster-network:
        ipv4_address: 172.18.0.9
    user: root
    ports:
      - 8081:8081
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  worker2:
    image: bitnami/spark:3.2.2
    container_name: worker2
    networks:
      cluster-network:
        ipv4_address: 172.18.0.10
    user: root
    ports:
      - 8082:8081
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  namenode:
    image: singularities/hadoop:2.8
    command: start-hadoop namenode
    hostname: namenode
    container_name: namenode
    networks:
      cluster-network:
        ipv4_address: 172.18.0.11
    environment:
      HDFS_USER: hdfsuser
    ports:
      - "8020:8020"
      - "9000:9000"
      - "50070:50070"
      - "50075:50075"
    depends_on:
      - zookeeper

    # datanode:
    #   image: singularities/hadoop:2.8
    #   command: start-hadoop datanode namenode
    #   hostname: datanode
    #   container_name: datanode
    #   environment:
    #     HDFS_USER: hdfsuser

#  conveyor:
#    image: registry.biubiubiu.io/turbine/conveyor:0.1.0
#    hostname: conveyor
#    container_name: conveyor
#    networks:
#      cluster-network:
#        ipv4_address: 172.18.0.12
#    ports:
#      - "9080:9080"