version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
      
  clickhouse:
    image: clickhouse/clickhouse-server:23.1.2.9
    container_name: clickhouse
    hostname: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./users.d:/etc/clickhouse-server/users.d
    ports:
      - 8123:8123
      - 9000:9000
      - 9004:9004