version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
  kettle:
    image: hiromuhota/webspoon
    container_name: kettle
    ports:
        - 8081:8080
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"