services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dbmate
      POSTGRES_USER: dbmate
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbmate -d dbmate"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
