# global config
global:
  scrape_interval:     15s  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout:      10s
  evaluation_interval: 15s  # Evaluate rules every 15 seconds. The default is every 1 minute.


scrape_configs:
  - job_name: 'go_client'
    scrape_interval: 5s  # 覆盖全局的 scrape_interval
    static_configs:
      - targets: ['client:2112']
