apiVersion: 1

datasources:
  - name: Prometheus
    id: 1
    orgId: 1
    uid: "da8c8729-cde5-4e48-a19d-3929806637d3"
    type: prometheus
    access: proxy
    isDefault: true
    readOnly: true
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.35.0
      queryTimeout: "5s"
      timeInterval: "5s"