version: '3'
services:
  mysql:
    image: mysql:5.7.16
    container_name: mysql
    hostname: mysql
    volumes:
      - ./my.cnf:/etc/my.cnf
    environment:
      - "MYSQL_ROOT_PASSWORD=Kuze123456!#%"
      - "MYSQL_DATABASE=grafana"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    depends_on:
      - mysql
    volumes:
      - ./mysql.yaml:/etc/grafana/provisioning/datasources/mysql.yaml
    environment:
      - "GRAFANA_MYSQL_PASSWORD=Kuze123456!#%"
    ports:
      - 3000:3000

  adminer:
    image: adminer:latest
    container_name: adminer
    hostname: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080
