version: '3'

volumes:
  kafka_1: {}

networks:
  test-net:
    ipam:
      config:
        - subnet: 172.30.0.0/24
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    networks:
      test-net:
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    restart: always
    container_name: kafka
    hostname: kafka
    networks:
      test-net:
        ipv4_address: 172.30.0.3
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - kafka_1:/bitnami/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092


  kafka2:
    image: 'bitnami/kafka:latest'
    restart: always
    container_name: kafka2
    hostname: kafka2
    networks:
      test-net:
        ipv4_address: 172.30.0.4
    depends_on:
      - zookeeper
    ports:
      - '9093:9092'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka2:9092

  kafka3:
    image: 'bitnami/kafka:latest'
    restart: always
    container_name: kafka3
    hostname: kafka3
    networks:
      test-net:
        ipv4_address: 172.30.0.5
    depends_on:
      - zookeeper
    ports:
      - '9094:9092'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka3:9092
