version: "3.7"

networks:
  redis-network:
    name: redis-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24

services:
  redis-cluster:
    image: redis:6-alpine
    command: 'redis-cli --cluster create 
    172.18.0.11:6379 172.18.0.12:6379 172.18.0.13:6379 172.18.0.14:6379 
    172.18.0.15:6379 172.18.0.16:6379
    --cluster-yes --cluster-replicas 1'
    networks:
      - redis-network
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6

  redis1:
    image: redis:6-alpine
    container_name: redis1
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.11
    expose:
      - 6379
    volumes:
      - $PWD/docker-data/redis1:/data
      - $PWD/docker-config/redis.conf:/usr/local/etc/redis/redis.conf

  redis2:
    image: redis:6-alpine
    container_name: redis2
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.12
    expose:
      - 6379
    volumes:
      - $PWD/docker-data/redis2:/data
      - $PWD/docker-config/redis.conf:/usr/local/etc/redis/redis.conf

  redis3:
    image: redis:6-alpine
    container_name: redis3
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.13
    expose:
      - 6379
    volumes:
      - $PWD/docker-data/redis3:/data
      - $PWD/docker-config/redis.conf:/usr/local/etc/redis/redis.conf

  redis4:
    image: redis:6-alpine
    container_name: redis4
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.14
    expose:
      - 6379
    volumes:
      - $PWD/docker-data/redis4:/data
      - $PWD/docker-config/redis.conf:/usr/local/etc/redis/redis.conf

  redis5:
    image: redis:6-alpine
    container_name: redis5
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.15
    expose:
      - 6379
    volumes:
      - $PWD/docker-data/redis5:/data
      - $PWD/docker-config/redis.conf:/usr/local/etc/redis/redis.conf

  redis6:
    image: redis:6-alpine
    container_name: redis6
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.18.0.16
    expose:
      - 6379
    volumes:
      - $PWD/docker-data/redis6:/data
      - $PWD/docker-config/redis.conf:/usr/local/etc/redis/redis.conf

  zookeeper:
    image: 'registry.biubiubiu.io/turbine/bitnami-zookeeper:3.7.0-debian-10-r215'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'registry.biubiubiu.io/turbine/bitnami-kafka:2.4.1-debian-10-r58'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=EXTERNAL_PLAINTEXT://:9092,INTERNAL_PLAINTEXT://:9093
      - KAFKA_ADVERTISED_LISTENERS=EXTERNAL_PLAINTEXT://127.0.0.1:9092,INTERNAL_PLAINTEXT://kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL_PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="my_topic"
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
