[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    debug
    storage.path /var/track/storage
    storage.sync normal
    storage.metrics off

[INPUT]
    Name              tail
    Path              /var/gen/*.log
    Tag               test-logs
    Refresh_Interval  300
    ignore_older      10m
    # DB file for tracking processed files
    DB                /var/track/tail-app.db
    # Reduce memory usage to trigger more aggressive cleanup
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On

[OUTPUT]
    Name   stdout
    Match  test-logs
    Format json
